name: PR Check

on:
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  test:
    name: Run Django Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django check
        run: |
          python manage.py check

      - name: Run tests
        run: |
          python manage.py test

      - name: Run PR Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            export PR_NUMBER=${{ github.event.pull_request.number }}
            export REPO="${{ github.repository }}"
          else
            export PR_NUMBER=${{ github.event.inputs.pr_number }}
            export REPO="${{ github.event.inputs.repo }}"
          fi

          python pr_analyzer.py --repo "$REPO" --pr "$PR_NUMBER"
