name: PR Check

on:
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  test:
    name: Run Django Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django check
        run: |
          python manage.py check

      - name: Run tests
        run: |
          python manage.py test
